_wandb:
    value:
        cli_version: 0.24.2
        e:
            k8xsjcx7gcfikwab406zzu8j4mbordvz:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 48
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "51539607552"
                args:
                    - --step
                    - train
                    - --use-wandb
                codePath: test.py
                codePathLocal: test.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "789330890752"
                executable: /Users/nielsrocholl/Documents/PhD DIAG - Local/Code/nnUNet-custom/venv/bin/python
                git:
                    commit: 0468ae8db3e2a4e22e959b9b2cd1055053fa7e4a
                    remote: git@github.com:nielsRocholl/nnUNet-v2-pro.git
                host: Mac.home
                memory:
                    total: "51539607552"
                os: macOS-26.2-arm64-arm-64bit-Mach-O
                program: /Users/nielsrocholl/Documents/PhD DIAG - Local/Code/nnUNet-custom/test.py
                python: CPython 3.13.5
                root: /Users/nielsrocholl/Documents/PhD DIAG - Local/Code/nnUNet-custom
                startedAt: "2026-02-09T10:40:32.353679Z"
                writerId: k8xsjcx7gcfikwab406zzu8j4mbordvz
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 61
            "4": 3.13.5
            "5": 0.24.2
            "12": 0.24.2
            "13": darwin-arm64
batch_size:
    value: 2
configuration:
    value: 3d_fullres
dataset_name:
    value: Dataset047_ULS23_Radboudumc_Pancreas
device:
    value: mps
fold:
    value: 0
initial_lr:
    value: 0.01
num_epochs:
    value: 1000
num_iterations_per_epoch:
    value: 250
num_val_iterations_per_epoch:
    value: 50
oversample_foreground_percent:
    value: 0.33
patch_size:
    value:
        - 64
        - 128
        - 128
spacing:
    value:
        - 3
        - 0.7568359375
        - 0.7568359375
trainer:
    value: nnUNetTrainer
